Update CI actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ jobs:
   # This workflow contains a single job called "build"
   build:
     # Build on the oldest supported ubuntu:
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -23,7 +23,9 @@ jobs:
     - uses: actions/checkout@v2
 
     - name: Install dependencies
-      run: sudo apt install libgtk2.0-dev libprocps-dev
+      run: |
+        sudo apt update
+        sudo apt install libgtk2.0-dev libprocps-dev
 
     - name: Build .deb package
       run: make deb
@@ -34,13 +36,23 @@ jobs:
         name: Debian packages
         path: '*.deb'
 
-    - name: Publish AUR package
-      uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
-      with:
-        pkgname: gatotray
-        pkgbuild: ./PKGBUILD
-        commit_username: gatopeich
-        commit_email: ${{ secrets.AUR_EMAIL }}
-        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
-        ssh_keyscan_types: rsa,ecdsa,ed25519
-        test: true
+  aur-publish:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Generate PKGBUILD
+        run: make PKGBUILD
+
+      - name: Publish AUR package
+        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
+        with:
+          pkgname: gatotray
+          pkgbuild: ./PKGBUILD
+          commit_username: gatopeich
+          commit_email: ${{ secrets.AUR_EMAIL }}
+          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
+          ssh_keyscan_types: rsa,ecdsa,ed25519
+          test: false
+          # test_flags: --clean --syncdeps
+          # post_process: gatotray || echo "Should fail by lack of DISPLAY"
